### ISSUE TITLE
Crash Starting Up

### ISSUE THREAD

**Issue by lartts** [Psychopathic-Dragon/Vanilla-Rubies#2]
Crash Report
[crash-2021-05-28_18.29.45-client.txt](https://github.com/Psychopathic-Dragon/Vanilla-Rubies/files/6560542/crash-2021-05-28_18.29.45-client.txt)

Log
[latest.log](https://github.com/Psychopathic-Dragon/Vanilla-Rubies/files/6560544/latest.log)

**Comment by Psychopathic-Dragon** [comment]
Should be good now, hopefully.
Thank you
